site_name: Backly API (BETA) Docs
pages:
    - About the API: index.md
    - Authentication: auth.md
    - Adverts (Messages):
      - Recent: adverts/recent.md
      - Create: adverts/create.md
    - Links: links.md
theme: readthedocs
